### PR TITLE
- test of linking to docs from README

### PR DESCRIPTION
**Pull request by okrieg**
deleted SPL code, and put workflow here, linked to README.  Lets get rid of wiki and just use this

### CODE REVIEW

**Comment by henn** [comment]
@okrieg - What do you think of the changes?

**Comment by okrieg** [comment]
We should link to this from the wiki as well

**Comment by zenhack** [comment]
.gitignore doesn't need to be there anymore; it's got a bunch of python-related things in it, and nothing currently relevant to this repository.

**Comment by zenhack** [comment]
I did a quick pass and some general cleanup, most of which is in commit 3aeedaf. Pay some attention to the style issues I raised specifically. Perhaps we should add something to the docs themselves regarding that sort of thing?

**Pull request merged**
